services:
  - type: web
    name: facturapro
    runtime: node
    plan: free
    buildCommand: curl -fsSL https://bun.sh/install | bash && bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: HOSTNAME
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: facturapro-db
          property: connectionString

databases:
  - name: facturapro-db
    plan: free
